# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
# allow passthrough to pass images to tmux
set -g allow-passthrough

# Change prefix key to Alt+a
set-option -g prefix M-a

# Change starting index of windows and panes to 1
set -g base-index 1
setw -g pane-base-index 1

# Increase session name
set -g status-left-length 30 # could be any number

# autofocus required by nvim checkhealth
set-option -g focus-events on

# bar on the top
set-option -g status-position top

# Allow mouse scroll
set -g mouse on # For newer tmux versions, >= 2.1


# hjkl navigation for panes
# taken from https://unix.stackexchange.com/questions/66745/tmux-remapping-keys-to-pane-on-the-left-right-top-down
# vim-like pane resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# and now unbind keys
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Load catppuccin
# not running catppuccin for now...
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# set -g @catppucin_flavor "mocha"
# set -g @catppuccin_window_status_style "rounded"
#
# # Make the status line pretty and add some modules
# set -g status-right-length 100
# set -g status-left-length 100
# set -g status-left ""
# set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# prevent auto scrolling after copying (after tpm to avoid being overridden).
bind -T copy-mode-vi y send-keys -X copy-selection-no-clear
bind -T copy-mode-vi Enter send-keys -X copy-selection-no-clear
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear
