from collections import deque
from types import TracebackType
from typing import Self

from .. import Message
from ..bus_messages import MatchRule

class FilterHandle:
    queue: deque[Message]
    def __enter__(self) -> deque[Message]: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...

class DBusConnection:
    unique_name: str
    def send_and_get_reply(self, message: Message, *, timeout: float | None = ...) -> Message: ...
    def filter(self, rule: MatchRule, *, queue: deque[Message] | None = ..., bufsize: int = ...) -> FilterHandle: ...
    def recv_until_filtered(self, queue: deque[Message], *, timeout: float | None = ...) -> Message: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...

def open_dbus_connection(bus: str = ..., enable_fds: bool = ..., auth_timeout: float = ...) -> DBusConnection: ...
